package com.leaptechjsc.game.happyfarm.assets;

import com.leaptechjsc.game.happyfarm.nature.F;

public class Language {

//    String languageVN, languageEn, languageCN, languageKR, languageCam, languageThai, languageLaos, languageMyanmar, languageIndo;
    public enum LANGU {
        VN,
        EN,
        CHINA,
        KOREAN,
        CAMBODIA,
        THAI,
        LAOS,
        MYANMAR,
        INDO
    }
/*
    public enum General {
        APP_NAME("Nông trại vui vẻ"
                , "Happy farm"
        ,"快乐农庄"
        ,"행복한 농장"
                ,"កសិដ្ឋានរីករាយ"
                ,""
                ,""
                ,""
                ,""),
        SETTING("Cài đặt"
                , "Setting"
        ,"设置"
                ,"설치하다"
                ,"ដំឡើង"
                ,""
                ,""
                ,""
                ,""),
        MUSIC("Nhạc nền"
                , "Music background"
        ,"背景音乐"
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        SOUND("Nhạc hiệu ứng"
                , "Sound effect"
                ,"音效"
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUY_GAME("Bạn có muốn mua 30.000 xu bằng tin nhắn giá 15.000 đồng không?\nHoặc nhấn \"khác\" để được mua ưu đãi hơn!"
                , "Do you want to purchase 30.000 coins by a message costs only 15.000 vnd?\nOr click \"other\" button to get other promotions"
        ,"你想购买30.000现金来关闭游戏中的广告吗？"
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        Information("Thông tin"
                , "Information"
                ,"信息"
                ,"정보"
                ,"ពត៌មាន"
                ,""
                ,""
                ,""
                ,""),
        NOT_ENOUGH_MONEY("Bạn không đủ tiền"
                , "You do not have enough money"
                ,"你没有足够的钱"
                ,"너는 충분한 돈이 없다"
                ,"អ្នកមិនមានលុយគ្រប់គ្រាន់ទេ"
                ,""
                ,""
                ,""
                ,""),
        NOT_ENOUGH_DIAMON("Bạn không đủ xu. Bạn có muốn mua xu không ?"
                , "You do not have enough coin. Do you want to purchase more coins?"
                ,"你没有足够的现金。你想购买更多现金吗？"
                ,"당신은 충분한 현금이 없습니다. 더 많은 현금을 사고 싶니?"
                ,"អ្នកមិនមានសាច់ប្រាក់គ្រប់គ្រាន់ទេ។. តើអ្នកចង់ទិញកាក់បន្ថែមទៀតទេ?"
                ,""
                ,""
                ,""
                ,""),
        BUY_GAME_OFF_AD("Bạn có muốn mua game với 30.000 xu để tắt quảng cáo không ?"
                , "Do you want to purchase 30.000 coins to turn off ads in game?"
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        EXIT_GAME("Bạn có chắc chắn muốn thoát game đang chơi không?"
                , "Are you sure to exit the game?"
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        SHARE_GAME("Chia sẻ game"
                , "Share this game"
        ,"分享这个游戏"
                ,"이 게임을 공유하십시오"
                ,""
                ,""
                ,""
                ,""
                ,""),
        SHARE_GAME_USER("Bạn có muốn giới thiệu game này cho người thân không?"
                , "Do you want to recommend this game to your family and friends?"
        ,"你想把这个游戏推荐给亲戚吗？"
                ,"이 게임을 친구에게 추천 하시겠습니까?"
                ,"ចែករំលែកហ្គេមនេះ"
                ,""
                ,""
                ,""
                ,""),
        TITLE_SHARE("Chơi game này đi, game này hay lắm"
                , "Let's play this game. It's fun."
        ,"让我们玩这个游戏。 好有趣。"
                ,"이 게임을하자. 재미 있습니다."
                ,"តោះលេងល្បែងនេះ។ វាសប្បាយណាស់។"
                ,""
                ,""
                ,""
                ,""),
        DOWNLOAD_HOT_GAME("Tải hot game"
                , "Install hot game"
        ,"下载热门游戏"
                ,"뜨거운 게임 설치"
                ,"ដំឡើងហ្គេមក្តៅ"
                ,""
                ,""
                ,""
                ,""),
        WANT_DOWNLOAD_HOT_GAME("Bạn có muốn tải hot game khác không?"
                , "Do you want to install other hot game?"
                ,"你想下载其他热门游戏吗？"
                ,"다른 핫 게임을 다운로드 하시겠습니까?"
                ,"តើអ្នកចង់ទាញយកល្បែងកម្សាន្តផ្សេងទៀតដែរឬទេ?"
                ,""
                ,""
                ,""
                ,""),
        GAME_OTHER("Game khác"
                , "Other games"
        ,"其他游戏"
                ,"다른 게임들"
                ,"ហ្គេមផ្សេងទៀត"
                ,""
                ,""
                ,""
                ,""),
        CLOSE("Đóng"
                , "Close"
        ,"关"
                ,"닫기"
                ,"បិត"
                ,""
                ,""
                ,""
                ,""),
        YES("Có"
                , "Yes"
        ,"同意"
                ,"동의하다"
                ,"យល់ស្រប"
                ,""
                ,""
                ,""
                ,""),
        NO("Không"
                , "No"
        ,"不同意"
                ,"동의하지 않는다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        FLOWER("Hoa"
                , "Flower"
        ,"花"
                ,"꽃"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_DONG_TIEN("Đồng tiền"
                , "Gerbera"
        ,"大丁草属"
                ,"거베라"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_LILY("Lily"
                , "Lily"
        ,"圣母百合"
                ,"백합"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_SEN("Sen"
                , "Lotus"
        ,"莲花"
                ,"로터스"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_TU_CAU("Tú cầu"
                , "Hydrangea"
        ,"绣球"
                ,"수국"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_CAM_CHUONG("Cẩm chướng"
                , "Carnation"
        ,"康乃馨"
                ,"카네이션"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_LILY_LOA_KEN("Lily loa ken"
                , "Lily"
        ,"马蹄莲"
                ,"카라 릴리"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_TRANG_NGUYEN("Trạng nguyên"
                , "Poinsettia"
        ,"一品红"
                ,"포 인 세 티아"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_HONG("Hồng"
                , "Rose"
        ,"玫瑰"
                ,"장미"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_HUONG_DUONG("Hướng dương"
                , "Sunflower"
        ,"向日葵"
                ,"해바라기"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_VIOLET("Violet"
                , "Violet"
        ,"堇菜属"
                ,"제비꽃속"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_BO_CONG_ANH("Bồ công anh"
                , "Dandelion"
        ,"蒲公英"
                ,"민들레"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOA_TULIP("Tulip"
                , "Tulip"
        ,"郁金香"
                ,"튤립"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BI_NGO("Bí ngô"
                , "Pumpkin"
        ,"南瓜"
                ,"호박"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CA_CHUA("Cà chua"
                , "Tomato"
        ,"番茄"
                ,"토마토"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CA_TIM("Cà tím"
                , "Eggplant"
        ,"茄子"
                ,"가지"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CAM("Cam"
                , "Orange"
        ,"桔子"
                ,"주황색"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CHUOI("Chuối"
                , "Banana"
        ,"香蕉"
                ,"바나나"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CU_CAI_TRANG("Củ cải trắng"
                , "White radish"
        ,"白萝卜"
                ,"흰 무"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DUA_HAU("Dưa hấu"
                , "Watermelon"
        ,"西瓜"
                ,"수박"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHO("Nho"
                , "Grape"
        ,"葡萄"
                ,"포도"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TAO("Táo"
                , "Apple"
        ,"苹果"
                ,"사과"
                ,""
                ,""
                ,""
                ,""
                ,""),
        XOAI("Xoài"
                , "Mango"
                ,"芒果"
                ,"망고"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DAU_TAY("Dâu tây"
                , "Strawberry"
        ,"草莓"
                ,"딸기"
                ,""
                ,""
                ,""
                ,""
                ,""),
        LE("Lê"
                , "Pear"
        ,"梨子"
                ,"배"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHAN_CONG("Nhân công"
                , "Farmer"
        ,"劳动"
                ,"노동"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BAN_BAN_NONG_SAN("Bàn bán nông sản"
                , "Farmer's kiosk"
        ,"农场亭"
                ,"농장 키오스크"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NGOC_MAY_MAN("Ngọc may mắn"
                , "Lucky gem"
        ,"幸运的宝石"
                ,"행운의 보석"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GIAY_BAO_DAM("Giấy bảo đảm"
                , "Warranty certificate"
        ,"保修凭证"
                ,"보증서"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GIA_MO_GD("Giá mở cửa giao dịch"
                , "The opening price of the transaction"
        ,"交易的开盘价"
                ,"무역의 개통 가격"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CHUA_DC_MO_TT("Bạn chưa thể mở thị trường này được"
                , "You can not open this market"
        ,"你还不能打开这个市场"
                ,"너는이 시장을 열 수 없다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HTNV_TANG_LO_NUOC("Hoàn thành nhiệm vụ bạn sẽ được tặng \n một lọ nước nâng cấp !"
                , "You will be given an upgrade level bottle \nwhen you complete the mission"
        ,"完成任务后，您将获得升级级别的瓶子"
                ,"퀘스트를 완료하면 업그레이드 레벨 병이 제공됩니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        TT_TAM_DUNG_GD("Trạng thái: Tạm dừng giao dịch"
                , "Status: Transaction closed"
        ,"状态：交易暂时关闭"
                ,"지위: 거래가 일시적으로 폐쇄되었습니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        TT_DANG_GD("Trạng thái: Đang giao dịch"
                , "Status: Transaction is progressing"
        ,"状态：交易正在进行"
                ,"지위 : 거래 진행 중"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GD_HOAN_THANH("Giao dịch hoàn thành"
                , "Transaction completed"
                ,"交易完成"
                ,"거래 완료"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NANG_CAP_TC("Nâng cấp thành công !"
                , "Upgraded successfully!"
        ,"升级成功！"
                ,"성공적으로 업그레이드되었습니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DAT_LV_MO_DAT("Để mở ô đất hiện tại bạn phải đạt level %d"
                , "You need to get level %d to open a new block"
        ,"您需要获得级别%的才能打开新块"
                ,"새 블록을 열려면 %d 레벨을 가져와야합니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        COMMING_SOON("Chức năng này hiện đang được phát triển !"
                , "This function is developing!"
        ,"这个功能正在发展！"
                ,"이 기능은 개발 중입니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MO_RONG_TC("Mở rộng thành công !"
                , "Expansion success!"
        ,"成功扩展！"
                ,"성공적으로 확장되었습니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MO_RONG_O_DAT("Mở rộng ô đất: "
                , "Expansion new block: "
        ,"展开新区块："
                ,"새 블록 확장 :"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HOAN_THANH_NV("Bạn đã hoàn thành nhiệm vụ"
                , "You have completed the mission"
        ,"你已经完成了任务"
                ,"너는 퀘스트를 완료했다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHIEM_VU("Nhiệm vụ"
                , "Mission"
        ,"任务"
                ,"사명"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DAP_UNG_NC_LT_QG("Đáp ứng nhu cầu kho lương thực quốc gia"
                , "Meet the demand of Nation Food Storage"
        ,"满足国家食品储存的需求"
                ,"국가 식품 저장 요구 사항 충족"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DAT_SOI("Đất sỏi"
                , "Gravel soil"
        ,"砾石土"
                ,"자갈 토양"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUI_CAY_XANH("Bụi cây xanh"
                , "Green bush"
        ,"绿色灌木"
                ,"녹색 덤불"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUI_CAY_TRANG("Bụi cây trắng"
                , "White bush"
        ,"白色的布什"
                ,"흰 덤불"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUI_CAY_VANG("Bụi cây vàng"
                , "Yellow bush"
        ,"黄色的布什"
                ,"노란 부시"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUI_CAY_DO("Bụi cây đỏ"
                , "Red bush"
        ,"红色的布什"
                ,"빨간 부시"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BUI_CAY_TIM("Bụi cây tím"
                , "Purple bush"
        ,"紫色的布什"
                ,"자주색 관목"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NANG_CAP_TC_LEN_CAP("Nâng cấp thành công lên cấp %d!"
                , "Upgraded successfully to level %d!"
                ,"成功升级到％d级！"
                ,"레벨 %d (으)로 성공적으로 업그레이드되었습니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NANG_CAP_THAT_BAI("Nâng cấp thất bại !"
                , "Upgrade failed!"
        ,"升级失败！"
                ,"업그레이드가 실패했습니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NANG_CAP_RUONG_D_LEN_CAP("Nâng cấp ruộng %d lên cấp!"
                , "Upgrade farm %d to level!"
        ,"将农场％d升级到水平！"
                ,"팜 %d을 (를) 수준으로 업그레이드하십시오!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        KHO_CHUA_HAT_GIONG("Kho chứa hạt giống"
                , "Store for seed"
        ,"种子储存"
                ,"종자 저장"
                ,""
                ,""
                ,""
                ,""
                ,""),
        THUE_1_NHAN_CONG("Thuê 1 nhân công tự động trồng trọt, chăn nuôi\nthu hoạch. Thuê trong 1 mùa"
                , "Hire 1 farmer to plant, to breed and harvest. Hire in 1 farming season."
        ,"雇佣1名农民种植，繁殖和收获。 在农耕季节租用。"
                ,"1 명의 농부를 고용하여 번식시키고 번식시키고 수확하십시오. 1 계절의 농업"
                ,""
                ,""
                ,""
                ,""
                ,""),
        THEM_1_CHO_BAN("Thêm 1 chỗ bán nông phẩm trong 1 mùa"
                , "Add 1 more kiosk in 1 farming season"
        ,"在一个季节添加一个销售农产品的地方"
                ,"계절에 농산물을 판매 할 장소를 추가하십시오."
                ,""
                ,""
                ,""
                ,""
                ,""),
        NGOC_MM_TANG_TC("Ngọc may mắn tăng thêm 20%\nkhả năng thành công"
                , "Lucky gem to get 20% of successful "
        ,"幸运宝石获得20％的成功"
                ,"성공의 20 %를 얻는 행운의 보석"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NC_TB_VUONG_0_GIAM("Nếu nâng cấp vườn thất bại thì\nvườn không bị giảm cấp"
                , "The farm will not be down level\nfor failing in upgrade level"
        ,"升级失败后，服务器场不会降级"
                ,"실패한 업그레이드를 위해 팜이 수준을 낮추지 않습니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        KHO_CHUA_NONG_PHAM("Kho chứa nông phẩm"
                , "Farm produce storage"
        ,"农产品存储"
                ,"농산물 저장"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CHON_NP_DE_BAN("Chọn nông phẩm để bán"
                , "Choose product to sell"
        ,"选择要销售的产品"
                ,"판매 할 제품 선택"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MUA_GAME_TC("Chúc mừng bạn đã mua game thành công !"
                , "Congratulation on purchasing game successfully!"
        ,"祝贺您成功购买游戏！"
                ,"게임을 성공적으로 구매하신 것을 축하합니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        KHONG_DU_XU_MUA_("Bạn không đủ xu để mua game !"
                , "You do not have enough coin to purchase this game!"
        ,"你没有足够的现金购买这个游戏！"
                ,"이 게임을 구입하기에 충분한 현금이 없습니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        YEAR("Năm"
                , "Year"
        ,"年"
                ,"년"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CHUNG_CU("Chung cư"
                , "Condominium"
        ,"共管"
                ,"분양 아파트"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CONG_VIEN("Công viên"
                , "Park"
        ,"公园"
                ,"공원"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CUA_HANG_CAFE("Cửa hàng\nCafe"
                , "Coffee shop"
        ,"咖啡店"
                ,"커피 샵"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CUA_HANG_FASTFOOD("Cửa hàng\nFastfood"
                , "Fastfood\nRestaurant"
        ,"快餐店"
                ,"패스트 푸드 레스토랑"
                ,""
                ,""
                ,""
                ,""
                ,""),
        KHACH_SAN("Khách sạn"
                , "Hotel"
        ,"旅馆"
                ,"호텔"
                ,""
                ,""
                ,""
                ,""
                ,""),
        KHO_LUONG_THUC("Kho lương thực"
                , "National Food Storage"
        ,"国家食品储存"
                ,"국가 식품 저장"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHA_GA("Nhà ga"
                , "Station"
        ,"站"
                ,"역"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHA_HANG_NHAT("Nhà hàng\nNhật"
                , "Japanese\nRestaurant"
        ,"日本餐厅"
                ,"일본 레스토랑"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TRUONG_HOC("Trường học"
                , "School"
        ,"学校"
                ,"학교"
                ,""
                ,""
                ,""
                ,""
                ,""),
        VAN_PHONG("Văn phòng"
                , "Office"
        ,"办公室"
                ,"사무실"
                ,""
                ,""
                ,""
                ,""
                ,""),
        VUON_HOA("Vườn hoa"
                , "Garden"
        ,"花园"
                ,"정원"
                ,""
                ,""
                ,""
                ,""
                ,""),
        VUON_THU("Vườn thú"
                , "Zoo"
        ,"动物园"
                ,"동물원"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CAP_DO("Cấp độ: "
                , "Level: "
        ,"水平："
                ,"수평:"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN("Hướng dẫn"
                , "Guide"
        ,"指南"
                ,"안내서"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_1("Cửa hàng: nơi bán hạt giống và vật phẩm"
                , "Shop: sell seeds and products"
        ,"商店：出售种子和产品"
                ,"상점 : 종자 및 제품 판매"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_2("Kho chứa: giúp kiểm tra số cây trồng còn lại"
                , "Storage: keeps the plants you have"
        ,"储存：保存您拥有的植物"
                ,"저장 : 가지고있는 식물 유지"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_3("Hạt giống: lấy hạt giống để trồng cây"
                , "Seed: seeds to plant the tree"
        ,"种子：种子种植树"
                ,"종자 : 나무 심는 씨앗"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_4("Cái xẻng: giúp nhổ bỏ cây trồng"
                , "Shovel: helps you to root up the trees"
        ,"铲：帮助你扎根树木"
                ,"삽 : 나무를 뿌리 내리는 데 도움이됩니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_5("Người giúp việc: điều chỉnh thứ tự\nưu tiên trồng các loại cây"
                , "Housekeeper: Helps you to arrange\nthe priority position of trees"
        ,"管家：帮助您安排树木的优先位置"
                ,"가정부 : 나무의 우선 순위를 정하는 데 도움을줍니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_6("Cuộn giấy: Xem thông tin nhiệm vụ\nhiện tại"
                , "Roll paper: to read the information\nof quests"
        ,"卷纸：阅读使命信息"
                ,"롤 용지 : 임무의 정보를 읽는"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_7("Thị trường sáng màu:\n    có thể giao dịch được"
                , "The bright market:\n    be able to trade"
        ,"光明的市场：可以交易"
                ,"밝은 시장 : 교역 할 수있다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_8("Thị trường tối màu:\n     chưa thể giao dich được"
                , "The dark market:\n    Not be able to trade"
        ,"黑市：无法交易"
                ,"어두운 시장 : 교역 할 수 없다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_9("Kho lương thực quốc gia:\n  nhiệm vụ cần làm trước khi\n     hết thời gian quy định"
                , "The National Food Storage:\n  Quest need to be done\n   before running out of time"
        ,"国家食品储存：任务需要在用完之前完成"
                ,"국가 식품 저장 : 시간이 부족하기 전에 퀘스트를 수행해야합니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        HUONG_DAN_10("Sau khi mở giao dịch\nbạn có thể tạm ngừng giao dịch nếu cần thiết"
                , "After opening a trade\nyou can pause it (if it is necessary)"
        ,"开盘后你可以暂时关闭它（如果有必要的话）"
                ,"거래를 한 후에는 일시적으로 거래를 마감 할 수 있습니다 (필요한 경우)."
                ,""
                ,""
                ,""
                ,""
                ,""),
        TAM_DUNG_MUA_BAN("Tạm dừng\nmua bán"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        TIEP_TUC_MUA_BAN("Tiếp tục\nmua bán"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        NONG_TRAI("Nông trại"
                , "Farm"
        ,"农场"
                ,"농장"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NONG_TRAI_DA_QUA("Nông trại đã qua %d mùa hạnh phục"
                , "The farm has passed %d the happy season"
        ,"农场度过了快乐的季节"
                ,"농장은 행복한 계절을 보냈습니다."
                ,""
                ,""
                ,""
                ,""
                ,""),
        XD_NT_TO_DEP("Tiếp tục xây dựng nông trại to đẹp hơn nữa!"
                , "Let's keep building a bigger and prettier farm!"
        ,"让我们继续建设一个更大，更漂亮的农场！"
                ,"더 크고 더 예쁜 농장을 짓 읍시다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        LEN_CAP("Lên cấp"
                , "Level up"
        ,"升级"
                ,"레벨 업"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HT_NHIEM_VU("Hoàn thành nhiệm vụ"
                , "Mission success"
        ,"完成任务"
                ,"임무 완수"
                ,""
                ,""
                ,""
                ,""
                ,""),
        DANG_YEU("Đáng yêu"
                , "Cute"
        ,"可爱"
                ,"귀엽다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GIAU_CO("Giàu có"
                , "Wealth"
        ,"财富"
                ,"풍부한"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HIEU_KHACH("Hiếu khách"
                , "Hospitable"
        ,"待客"
                ,"환대"
                ,""
                ,""
                ,""
                ,""
                ,""),
        VUI_VE("Vui vẻ"
                , "Cheerful"
        ,"高兴"
                ,"쾌활한"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HANH_PHUC("Hạnh phúc"
                , "Happy"
        ,"快乐"
                ,"행복"
                ,""
                ,""
                ,""
                ,""
                ,""),
        THAN_THIEN("Thân thiện"
                , "Nice"
        ,"可亲"
                ,"좋은"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TANG_1_NC_THAN("Tặng 1 nước thần"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        QUA_TANG_TAN_GIA("QÙA TẶNG TÂN GIA"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        PHUT_GIAY_VUI_VE("Hi vọng bạn sẽ có\nnhững phút giây\nthật sự vui vẻ !"
                , ""
        ,"希望你有幸福的时刻！"
                ,"행복한 순간을 가지기를 바랍니다!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        HET_GIO_SD_NHAN_CONG("Hết thời gian sử dụng\nnhân công tự động.\n\n Để sử dụng \t\t\t\t\t\nhân công tự \nđộng bạn hãy vào cửa hàng \nđể mua nhé !"
                , "You cannot use automatic farmer now. Go to shop now!"
        ,"你现在不能使用自动农民。 现在去购物！"
                ,"지금 자동 농부는 사용할 수 없습니다. 지금 가게에 가세요!"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NUOC_THAN("Nước thần"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        MUA_XUAN("Mùa xuân"
                , "Spring"
        ,"春天"
                ,"봄"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MUA_HA("Mùa hạ"
                , "Summer"
        ,"夏天"
                ,"여름"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MUA_THU("Mùa thu"
                , "Autumn"
        ,"秋天"
                ,"가을"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MUA_DONG("Mùa đông"
                , "Winter"
        ,"冬季"
                ,"겨울"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TAM_DUNG("Tạm dừng"
                , "Pause"
        ,"暂停"
                ,"중지"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NANG_CAP("Nâng cấp"
                , "Upgrade"
        ,"升级"
                ,"업그레이드"
                ,""
                ,""
                ,""
                ,""
                ,""),
        CHI_PHI("Chi phí"
                , "Cost"
        ,"成本"
                ,"비용"
                ,""
                ,""
                ,""
                ,""
                ,""),
        SU_DUNG_THEM("Sử dụng thêm"
                , "Use more"
        ,"使用更多"
                ,"더 많이 사용하다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TANG("Tăng"
                , "Up"
        ,"向上"
                ,"쪽으로"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GIAM("Giảm"
                , "Down"
        ,"向下"
                ,"하위"
                ,""
                ,""
                ,""
                ,""
                ,""),
        KINH_NGHIEM_KHI_THU("Kinh nghiệm khi thu hoạch"
                , "Experience in harvest"
        ,"丰收经验"
                ,"수확 체험"
                ,""
                ,""
                ,""
                ,""
                ,""),
        THOI_GIAN_KHI_THU("Thời gian khi thu hoạch"
                , "Time to harvest"
        ,"是时候收获了"
                ,"수확 할 시간"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MO_RONG_DAT("Mở rộng đất"
                , "Expand the land"
        ,"扩大土地"
                ,"땅을 넓히다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        MO_RONG("Mở rộng"
                , "Expand"
        ,"扩大"
                ,"넓히다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        BN_MUON_NHO_CAY("Bạn muốn nhổ cây đi hay không?"
                , "Do you want to root up the tree?"
        ,"你想要树根吗？"
                ,"나무를 뿌리 치고 싶니?"
                ,""
                ,""
                ,""
                ,""
                ,""),
        GIA_BAN_NHANH("Giá bán nhanh"
                , ""
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        NHAP_SO_LUONG("Nhập số lượng"
                , "Enter the quantity"
        ,"输入数量"
                ,"수량 입력"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TONG_SO_TIEN("Tổng số tiền"
                , "Total Money"
        ,"总价"
                ,"총 가격"
                ,""
                ,""
                ,""
                ,""
                ,""),
        NAP_XU("Nạp xu"
                , "Deposit coin"
        ,"存款现金"
                ,"예금 현금"
                ,""
                ,""
                ,""
                ,""
                ,""),
        TXT_NHAN("Nhận"
                , "Receive"
        ,"接收"
                ,"받다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        Confirm("Xác nhận"
                , "Confirm"
        ,"确认"
                ,"확인하다"
                ,""
                ,""
                ,""
                ,""
                ,""),
        ADD_MONEY_VIEW_AD("Bạn nhận được %d xu!"
                , "You recive %d money!"
        ,""
                ,""
                ,""
                ,""
                ,""
                ,""
                ,""),
        Accept("Đồng ý"
                , "Accept"
        ,"接受"
                ,"받아 들인다"
                ,""
                ,""
                ,""
                ,""
                ,"");
                */

public enum General{
    APP_NAME("Nông trại vui vẻ"
            ,"Happy farm"
            ,"快乐农庄"
            ,"행복한 농장"
            ,"កសិដ្ឋានរីករាយ"
            ,"ฟาร์มแห่งความสุข"
            ,"ກະສິກໍາທີ່ດີໃຈ"
            ,"မင်္ဂလာခြံ"
            ,"Selamat bertani"),
    SETTING("Cài đặt"
            ,"Setting"
            ,"设置"
            ,"설치하다"
            ,"ដំឡើង"
            ,"ติดตั้ง"
            ,"ຕິດຕັ້ງ"
            ,"အင်စတော်လေးရှင်း"
            ,"Memasang"),
    MUSIC("Nhạc nền"
            ,"Background music"
            ,"背景音乐"
            ,"배경 음악"
            ,"តន្ត្រីផ្ទៃខាងក្រោយ"
            ,"เพลงพื้นหลัง"
            ,"ດົນຕີພື້ນຖານ"
            ,"နောက်ခံတေးဂီတ"
            ,"latarbelakang musik"),
    SOUND("Nhạc hiệu ứng"
            ,"Sound effect"
            ,"音效"
            ,"음향 효과"
            ,"ប្រសិទ្ធិភាពសំឡេង"
            ,"เสียงประกอบ"
            ,"ຜົນກະທົບສຽງ"
            ,"အသံအကျိုးသက်ရောက်မှု"
            ,"Efek suara"),
    BUY_GAME("Bạn có muốn mua 30.000 xu bằng tin nhắn giá 15.000 đồng không?\nHoặc nhấn \"khác\" để được mua ưu đãi hơn!"
            ,"Buy game"
            ,"买游戏"
            ,"게임 구매"
            ,"ទិញល្បែង"
            ,"ซื้อเกม"
            ,"ຊື້ເກມ"
            ,"ဂိမ်းကိုဝယ်"
            ,"Beli game"),
    Information("Thông tin"
            ,"Information"
            ,"信息"
            ,"정보"
            ,"ពត៌មាន"
            ,"ข้อมูล"
            ,"ຂໍ້ມູນຂ່າວສານ"
            ,"သတင်းအချက်အလက်"
            ,"informasi"),
    NOT_ENOUGH_MONEY("Bạn không đủ tiền"
            ,"You do not have enough money"
            ,"你没有足够的钱"
            ,"너는 충분한 돈이 없다"
            ,"អ្នកមិនមានលុយគ្រប់គ្រាន់ទេ"
            ,"คุณไม่มีเงินเพียงพอ"
            ,"ທ່ານບໍ່ມີເງິນພຽງພໍ"
            ,"သငျသညျငွေအလုံအလောက်မရှိကြပါဘူး"
            ,"Kamu tidak punya cukup uang"),
    NOT_ENOUGH_DIAMON("Bạn không đủ xu. Bạn có muốn mua xu không ?"
            ,"You do not have enough cash. Do you want to purchase more cash?"
            ,"你没有足够的现金。你想购买更多现金吗？"
            ,"당신은 충분한 현금이 없습니다. 더 많은 현금을 사고 싶니?"
            ,"អ្នកមិនមានសាច់ប្រាក់គ្រប់គ្រាន់ទេ។. តើអ្នកចង់ទិញកាក់បន្ថែមទៀតទេ?"
            ,"คุณไม่มีเงินสดเพียงพอ. តើអ្នកចង់ទិញសាច់ប្រាក់បន្ថែមដែរឬទេ?"
            ,"ທ່ານບໍ່ມີເງິນສົດພຽງພໍ. ທ່ານຕ້ອງການຊື້ເງິນສົດເພີ່ມເຕີມບໍ?"
            ,"သငျသညျအလုံအလောက်ငွေမရှိကြပါဘူး။. သင်ပိုမိုငွေသားဝယ်ယူချင်ပါသလား?"
            ,"Anda tidak memiliki cukup uang tunai. Apakah Anda ingin membeli lebih banyak uang?"),
    BUY_GAME_OFF_AD("Bạn có muốn mua game với 30.000 xu để tắt quảng cáo không ?"
            ,"Would you like to purchase 30.000 cash to turn off ads in game?"
            ,"你想购买30.000现金来关闭游戏中的广告吗？"
            ,"게임에서 광고를 끄려면 30,000 원의 현금을 사고 싶습니까?"
            ,"តើអ្នកចង់ទិញ 30.000 សាច់ប្រាក់ដើម្បីបិទពាណិជ្ជកម្មនៅក្នុងហ្គេមទេ?"
            ,"คุณต้องการซื้อเงินสด 30,000 เพื่อปิดโฆษณาในเกมหรือไม่?"
            ,"ທ່ານຕ້ອງການຊື້ 30.000 ເງິນສົດເພື່ອປິດການໂຄສະນາໃນເກມ?"
            ,"သငျသညျဂိမ်းထဲမှာကြော်ငြာတွေကို turn off မှ 30,000 ငွေသားဝယ်ယူလိုပါသလား"
            ,"Apakah Anda ingin membeli 30.000 uang tunai untuk mematikan iklan dalam game?"),
    EXIT_GAME("Bạn có chắc chắn muốn thoát game đang chơi không?"
            ,"Are you sure to exit the game?"
            ,"你确定退出游戏吗？"
            ,"게임을 종료 하시겠습니까?"
            ,"តើអ្នកប្រាកដជាចាកចេញពីហ្គេមមែនទេ?"
            ,"คุณแน่ใจหรือว่าจะออกจากเกม?"
            ,"ທ່ານແນ່ໃຈທີ່ຈະອອກຈາກເກມ?"
            ,"ဂိမ်းမှထွက်ရန်သေချာလား?"
            ,"Apakah Anda yakin untuk keluar dari permainan?"),
    SHARE_GAME("Chia sẻ game"
            ,"Share this game"
            ,"分享这个游戏"
            ,"이 게임을 공유하십시오"
            ,"ចែករំលែកហ្គេមនេះ"
            ,"แบ่งปันเกมนี้"
            ,"ແບ່ງປັນເກມນີ້"
            ,"ဒီဂိမ်းကိုမျှဝေရန်"
            ,"Bagikan game ini"),
    SHARE_GAME_USER("Bạn có muốn giới thiệu game này cho người thân không?"
            ,"Would you like to recommend this game to your family and friends?"
            ,"你想把这个游戏推荐给亲戚吗？"
            ,"이 게임을 친구에게 추천 하시겠습니까?"
            ,"តើអ្នកនឹងផ្ដល់អនុសាសន៍ហ្គេមនេះទៅមិត្តរបស់អ្នកទេ?"
            ,"คุณต้องการแนะนำเกมนี้กับครอบครัวและเพื่อนของคุณหรือไม่?"
            ,"ທ່ານຢາກແນະນໍາເກມນີ້ໃຫ້ແກ່ຄອບຄົວແລະຫມູ່ເພື່ອນຂອງທ່ານບໍ?"
            ,"သင်သည်သင်၏မိသားစုနှင့်မိတ်ဆွေများကိုဤဂိမ်းကိုအကြံပြုလိုပါသလား"
            ,"Apakah Anda ingin merekomendasikan game ini kepada keluarga dan teman-teman Anda?"),
    TITLE_SHARE("Chơi game này đi, game này hay lắm"
            ,"Let's play this game. It's fun."
            ,"让我们玩这个游戏。 好有趣。"
            ,"이 게임을하자. 재미 있습니다."
            ,"តោះលេងល្បែងនេះ។ វាសប្បាយណាស់។"
            ,"ลองเล่นเกมนี้กันเถอะ มันสนุก."
            ,"ໃຫ້ຫລິ້ນເກມນີ້. ມັນ​ມ່ວນ."
            ,"ဒီဂိမ်းကိုဆော့ကစားကြကုန်အံ့။ ဒါဟာပျော်စရာပါပဲ။"
            ,"Ayo mainkan game ini. Itu menyenangkan."),
    DOWNLOAD_HOT_GAME("Tải hot game"
            ,"Download hot game"
            ,"下载热门游戏"
            ,"뜨거운 게임 설치"
            ,"ដំឡើងហ្គេមក្តៅ"
            ,"ดาวน์โหลดเกมร้อน"
            ,"ດາວໂຫລດເກມຮ້ອນ"
            ,"ပူပြင်းတဲ့ဂိမ်းဒေါင်းလုဒ်"
            ,"Pasang game panas"),
    WANT_DOWNLOAD_HOT_GAME("Bạn có muốn tải hot game khác không?"
            ,"Would you like to download other hot game?"
            ,"你想下载其他热门游戏吗？"
            ,"다른 핫 게임을 다운로드 하시겠습니까?"
            ,"តើអ្នកចង់ទាញយកល្បែងកម្សាន្តផ្សេងទៀតដែរឬទេ?"
            ,"คุณต้องการดาวน์โหลดเกมอื่น ๆ ร้อน?"
            ,"ທ່ານຕ້ອງການດາວໂຫລດເກມຮ້ອນອື່ນໆບໍ?"
            ,"သင်သည်အခြားပူဂိမ်းဒေါင်းလုဒ်ဆွဲချင်ကြသနည်း"
            ,"apakah Anda ingin mengunduh permainan panas lainnya?"),
    GAME_OTHER("Game khác"
            ,"Other games"
            ,"其他游戏"
            ,"다른 게임들"
            ,"ហ្គេមផ្សេងទៀត"
            ,"เกมอื่น ๆ"
            ,"ເກມອື່ນໆ"
            ,"သည်အခြားဂိမ်း"
            ,"Game lainnya"),
    CLOSE("Đóng"
            ,"Close"
            ,"关"
            ,"닫기"
            ,"បិត"
            ,"ปิด"
            ,"ປິດ"
            ,"ပိတ်"
            ,"menutup"),
    YES("Có"
            ,"Yes"
            ,"同意"
            ,"동의하다"
            ,"យល់ស្រប"
            ,"ตกลง"
            ,"ຍອມຮັບ"
            ,"သဘောတူ"
            ,"setuju"),
    NO("Không"
            ,"No"
            ,"不同意"
            ,"동의하지 않는다"
            ,"មិនយល់ស្រប"
            ,"ไม่เห็นด้วย"
            ,"ບໍ່ເຫັນດີນໍາ"
            ,"သဘောကှဲ"
            ,"tidak setuju"),
    FLOWER("Hoa"
            ,"Flower"
            ,"花"
            ,"꽃"
            ,"ផ្កា"
            ,"ดอกไม้"
            ,"ດອກໄມ້"
            ,"ပန်း"
            ,"bunga"),
    HOA_DONG_TIEN("Đồng tiền"
            ,"Gerbera"
            ,"大丁草属"
            ,"거베라"
            ,"Gerbera"
            ,"เยอบีร่า"
            ,"Gerbera"
            ,"Gerbera"
            ,"Herbras"),
    HOA_LILY("Lily"
            ,"Madonna lily"
            ,"圣母百合"
            ,"백합"
            ,"Madonna lily"
            ,"Madonna lily"
            ,"Madonna lily"
            ,"Madonna lily"
            ,"Bunga lily"),
    HOA_SEN("Sen"
            ,"Lotus"
            ,"莲花"
            ,"로터스"
            ,"ផ្កាឈូក"
            ,"ดอกบัว"
            ,"ດອກບົວ"
            ,"ကြာပန်း"
            ,"bunga teratai"),
    HOA_TU_CAU("Tú cầu"
            ,"Hydrangea"
            ,"绣球"
            ,"수국"
            ,"ហារដាន"
            ,"พืชไม้ดอกขนาดใหญ่"
            ,"Hydrangea"
            ,"Hydrangea"
            ,"Hortensia"),
    HOA_CAM_CHUONG("Cẩm chướng"
            ,"Carnation"
            ,"康乃馨"
            ,"카네이션"
            ,"ផ្កាការនាស"
            ,"ดอกคาร์เนชั่น"
            ,"ດອກໄມ້ດອກໄມ້"
            ,"ဇော်မွှားပန်း"
            ,"Anyelir"),
    HOA_LILY_LOA_KEN("Lily loa ken"
            ,"Calla lily"
            ,"马蹄莲"
            ,"카라 릴리"
            ,"Calla lily"
            ,"แคลลาลิลลี่"
            ,"Calla lily"
            ,"Calla lily"
            ,"Kala lili"),
    HOA_TRANG_NGUYEN("Trạng nguyên"
            ,"Poinsettia"
            ,"一品红"
            ,"포 인 세 티아"
            ,"Poinsettia"
            ,"Poinsettia"
            ,"Poinsettia"
            ,"Poinsettia"
            ,"Kastuba"),
    HOA_HONG("Hồng"
            ,"Rose"
            ,"玫瑰"
            ,"장미"
            ,"ផ្កាកុលាប"
            ,"ดอกกุหลาบ"
            ,"ດອກກຸຫລາບ"
            ,"နှင်းဆီပင်"
            ,"Mawar"),
    HOA_HUONG_DUONG("Hướng dương"
            ,"Sunflower"
            ,"向日葵"
            ,"해바라기"
            ,"ផ្កាឈូករ័ត្ន"
            ,"ดอกทานตะวัน"
            ,"ດອກຕາເວັນ"
            ,"နေကြာ"
            ,"bunga matahari"),
    HOA_VIOLET("Violet"
            ,"Viola"
            ,"堇菜属"
            ,"제비꽃속"
            ,"ពណ៌ស្វាយ"
            ,"สีม่วง"
            ,"ສີມ່ວງ"
            ,"ခရမ်းရောင်"
            ,"bunga violet"),
    HOA_BO_CONG_ANH("Bồ công anh"
            ,"Dandelion"
            ,"蒲公英"
            ,"민들레"
            ,"Dandelion"
            ,"ดอกแดนดิไล"
            ,"Dandelion"
            ,"Dandelion"
            ,"Randa Tapak"),
    HOA_TULIP("Tulip"
            ,"Tulip"
            ,"郁金香"
            ,"튤립"
            ,"ផ្កាតុលីប"
            ,"พืชไม้ดอกขนาดใหญ่มีรูปคล้ายถ้วยหรือระฆัง"
            ,"ດອກທິວລິບ"
            ,"နှင်းပန်း"
            ,"bunga tulp"),
    BI_NGO("Bí ngô"
            ,"Pumpkin"
            ,"南瓜"
            ,"호박"
            ,"ល្ពៅ"
            ,"ฟักทอง"
            ,"ໝາກອຶ"
            ,"ရှေဖရုံသီး"
            ,"labu kuning"),
    CA_CHUA("Cà chua"
            ,"Tomato"
            ,"番茄"
            ,"토마토"
            ,"ប៉េងប៉ោះ"
            ,"มะเขือเทศ"
            ,"ຫມາກ​ເລັ່ນ"
            ,"ခရမ်းချဉ်သီး"
            ,"tomat"),
    CA_TIM("Cà tím"
            ,"Eggplant"
            ,"茄子"
            ,"가지"
            ,"eggplant"
            ,"มะเขือ"
            ,"ຫມາກ​ເຂືອ"
            ,"ခရမ်းသီး"
            ,"terong"),
    CAM("Cam"
            ,"Orange"
            ,"桔子"
            ,"주황색"
            ,"ទឹកក្រូច"
            ,"ส้ม"
            ,"ໝາກກ້ຽງ"
            ,"လိမ္မော်သီး"
            ,"Jeruk"),
    CHUOI("Chuối"
            ,"Banana"
            ,"香蕉"
            ,"바나나"
            ,"ចេក"
            ,"กล้วย"
            ,"ກ້ວຍ"
            ,"ငှက်ပျောသီး"
            ,"pisang"),
    CU_CAI_TRANG("Củ cải trắng"
            ,"White radish"
            ,"白萝卜"
            ,"흰 무"
            ,"ស្ពៃមើម"
            ,"หัวผักกาด"
            ,"ຫົວຜັກກາດ"
            ,"မုန်လာဉဝါ"
            ,"lobak"),
    DUA_HAU("Dưa hấu"
            ,"Watermelon"
            ,"西瓜"
            ,"수박"
            ,"ឪឡឹក"
            ,"แตงโม"
            ,"ຫມາກໂມ"
            ,"ဖရဲသီး"
            ,"semangka"),
    NHO("Nho"
            ,"Grape"
            ,"葡萄"
            ,"포도"
            ,"ទំពាំងបាយជូ"
            ,"องุ่น"
            ,"ໝາກອະງົ່ນ"
            ,"စပျစ်သီး"
            ,"buah anggur"),
    TAO("Táo"
            ,"Apple"
            ,"苹果"
            ,"사과"
            ,"ផ្លែប៉ោម"
            ,"ลูกแอปเปิ้ล"
            ,"ຫມາກໂປມ"
            ,"ပန်းသီး"
            ,"buah apel"),
    XOAI("Xoài"
            ,"Mango"
            ,"芒果"
            ,"망고"
            ,"ស្វាយ"
            ,"มะม่วง"
            ,"ຫມາກມ່ວງ"
            ,"သရက်သီး"
            ,"mangga"),
    DAU_TAY("Dâu tây"
            ,"Strawberry"
            ,"草莓"
            ,"딸기"
            ,"ផ្លេរស្ដូវបេរី"
            ,"สตรอเบอร์รี่"
            ,"ໝາກມອນຊະນິດໜຶ່ງ"
            ,"စတော်ဘယ်ရီ"
            ,"stroberi"),
    LE("Lê"
            ,"Pear"
            ,"梨子"
            ,"배"
            ,"ផ្លេផ្យេរ"
            ,"ลูกแพร์"
            ,"ໝາກກ້ຽງເທດ"
            ,"သစ်တော်သီး"
            ,"pir"),
    NHAN_CONG("Nhân công"
            ,"Labor"
            ,"劳动"
            ,"노동"
            ,"ពលកម្ម"
            ,"แรงงาน"
            ,"ແຮງ​ງານ"
            ,"အလုပ်"
            ,"tenaga kerja"),
    BAN_BAN_NONG_SAN("Bàn bán nông sản"
            ,"Farm kiosk"
            ,"农场亭"
            ,"농장 키오스크"
            ,"ហាងកាហ្វេ"
            ,"ตู้ฟาร์ม"
            ,"ຕາຕະລາງກະສິກໍາ"
            ,"လယ်ယာစားပွဲပေါ်မှာ"
            ,"kios pertanian"),
    NGOC_MAY_MAN("Ngọc may mắn"
            ,"Lucky gem"
            ,"幸运的宝石"
            ,"행운의 보석"
            ,"គ្រឿងអលង្ការសំណាង"
            ,"อัญมณีที่โชคดี"
            ,"ຫິນທີ່ໂຊກດີ"
            ,"ကံကောင်းရတနာ"
            ,"permata yang beruntung"),
    GIAY_BAO_DAM("Giấy bảo đảm"
            ,"Warranty certificate"
            ,"保修凭证"
            ,"보증서"
            ,"វិញ្ញាបនបត្រធានា"
            ,"ใบรับรองการรับประกัน"
            ,"ໃບຢັ້ງຢືນການຮັບປະກັນ"
            ,"အာမခံလက်မှတ်"
            ,"sertifikat garansi"),
    GIA_MO_GD("Giá mở cửa giao dịch"
            ,"The opening price of the trade"
            ,"交易的开盘价"
            ,"무역의 개통 가격"
            ,"តម្លៃបើកចំហនៃពាណិជ្ជកម្ម"
            ,"ราคาเปิดของการค้า"
            ,"ລາຄາເປີດຂອງການຄ້າ"
            ,"ကုန်သွယ်ရေး၏အဖွင့်သောစျေးနှုန်း"
            ,"harga pembukaan perdagangan"),
    CHUA_DC_MO_TT("Bạn chưa thể mở thị trường này được"
            ,"You can not open this market"
            ,"你还不能打开这个市场"
            ,"너는이 시장을 열 수 없다."
            ,"អ្នកមិនអាចបើកទីផ្សារនេះបានទេ"
            ,"คุณไม่สามารถเปิดตลาดนี้ได้"
            ,"ທ່ານບໍ່ສາມາດເປີດຕະຫຼາດນີ້"
            ,"သင်ဤဈေးကွက်ဖွင့်လို့မရဘူး"
            ,"Anda tidak dapat membuka pasar ini"),
    HTNV_TANG_LO_NUOC("Hoàn thành nhiệm vụ bạn sẽ được tặng \n một lọ nước nâng cấp !"
            ,"You will be given an upgrade level bottle when you complete the quest"
            ,"完成任务后，您将获得升级级别的瓶子"
            ,"퀘스트를 완료하면 업그레이드 레벨 병이 제공됩니다."
            ,"អ្នកនឹងត្រូវបានផ្តល់ដបកម្រិតខ្ពស់មួយនៅពេលអ្នកបញ្ចប់ដំណើរស្វែងរក"
            ,"คุณจะได้รับขวดอัพเกรดระดับเมื่อคุณเสร็จสิ้นการแสวงหา"
            ,"ທ່ານຈະໄດ້ຮັບແກ້ວລະດັບການຍົກລະດັບເມື່ອທ່ານເຮັດສໍາເລັດ"
            ,"သငျသညျ ပြီးဆုံးတဲ့အခါသင်ထားတဲ့အဆင့်မြှင့်အဆင့်အထိပုလင်းပေးတော်မူလတံ့ "
            ,"Anda akan diberi botol tingkat upgrade ketika Anda menyelesaikan quest"),
    TT_TAM_DUNG_GD("Trạng thái: Tạm dừng giao dịch"
            ,"Status: Trading Temporarily Closed"
            ,"状态：交易暂时关闭"
            ,"지위: 거래가 일시적으로 폐쇄되었습니다."
            ,"ស្ថានភាព: ការធ្វើពាណិជ្ជកម្មបានបិទជាបណ្តោះអាសន្ន"
            ,"สถานะ: ปิดการซื้อขายชั่วคราว"
            ,"ສະຖານະ: ການຊື້ຂາຍປິດຊົ່ວຄາວ"
            ,"အခွအေနေ: ကုန်သွယ်ယာယီပိတ်သိမ်း"
            ,"keadaan: perdagangan sementara ditutup"),
    TT_DANG_GD("Trạng thái: Đang giao dịch"
            ,"Status: Trading is in progress"
            ,"状态：交易正在进行"
            ,"지위 : 거래 진행 중"
            ,"ស្ថានភាព: ការជួញដូរកំពុងដំណើរការ"
            ,"สถานะ: กำลังดำเนินการซื้อขาย"
            ,"ສະຖານະ: ການຊື້ຂາຍແມ່ນຢູ່ໃນຄວາມຄືບຫນ້າ"
            ,"အခွအေနေ: ထရေးဒင်းတိုးတက်မှုအတွက်ဖြစ်ပါသည်"
            ,"keadaan: Perdagangan sedang berlangsung"),
    GD_HOAN_THANH("Giao dịch hoàn thành"
            ,"Trading completed"
            ,"交易完成"
            ,"거래 완료"
            ,"ការជួញ ដូរបានបញ្ចប់"
            ,"การซื้อขายเสร็จสิ้นแล้ว"
            ,"ຊື້ຂາຍແລ້ວສົມບູນ"
            ,"ထရေးဒင်းပြီးစီး"
            ,"Perdagangan selesai"),
    NANG_CAP_TC("Nâng cấp thành công !"
            ,"Upgraded successfully!"
            ,"升级成功！"
            ,"성공적으로 업그레이드되었습니다!"
            ,"បានដំឡើងកំណែដោយជោគជ័យ!"
            ,"อัพเกรดแล้ว!"
            ,"ອັບເກດທີ່ປະສົບຄວາມສໍາເລັດ!"
            ,"အောင်မြင်စွာအဆင့်မြှင့်!"
            ,"Berhasil ditingkatkan!"),
    DAT_LV_MO_DAT("Để mở ô đất hiện tại bạn phải đạt level %d"
            ,"You need to get level %d to open a new block"
            ,"您需要获得级别%的才能打开新块"
            ,"새 블록을 열려면 % d 레벨을 가져와야합니다."
            ,"អ្នកត្រូវទទួលបានកម្រិត% d ដើម្បីបើកប្លុកថ្មី"
            ,"คุณต้องได้รับ% d ระดับเพื่อเปิดบล็อกใหม่"
            ,"ທ່ານຈໍາເປັນຕ້ອງໄດ້ຮັບລະດັບ% d ເພື່ອເປີດບລັອກໃຫມ່"
            ,"သငျသညျသစ်တစ်ခုပိတ်ပင်တားဆီးမှုဖွင့်ဖို့အဆင့်ကို% ဃရနျလိုအပျ"
            ,"Anda perlu mendapatkan level% d untuk membuka blok baru"),
    COMMING_SOON("Chức năng này hiện đang được phát triển !"
            ,"This feature is developing!"
            ,"这个功能正在发展！"
            ,"이 기능은 개발 중입니다!"
            ,"លក្ខណៈពិសេសនេះកំពុងអភិវឌ្ឍ!"
            ,"คุณลักษณะนี้กำลังพัฒนา!"
            ,"ຄຸນນະສົມບັດນີ້ແມ່ນການພັດທະນາ!"
            ,"ဤသည်မှာဆောင်ရွက်ဖွံ့ဖြိုးဆဲနေပါသည်!"
            ,"Fitur ini berkembang!"),
    MO_RONG_TC("Mở rộng thành công !"
            ,"Expanded successfully!"
            ,"成功扩展！"
            ,"성공적으로 확장되었습니다!"
            ,"បានពង្រីកដោយជោគជ័យ!"
            ,"ขยายสำเร็จแล้ว!"
            ,"ການຂະຫຍາຍ ສົບຜົນສໍາເລັດ!"
            ,"ကျယ်ပြန့်ကိုအောင်မြင်စွာ!"
            ,"Berhasil diperluas!"),
    MO_RONG_O_DAT("Mở rộng ô đất:"
            ,"Expand new block:"
            ,"展开新区块："
            ,"새 블록 확장 :"
            ,"ពង្រីកប្លុកថ្មី:"
            ,"ขยายบล็อกใหม่:"
            ,"ຂະຫຍາຍບລັອກໃຫມ່:"
            ,"ကျယ်ပြန့်သစ်ကိုပိတ်ပင်တားဆီးမှု:"
            ,"Perluas blok baru:"),
    HOAN_THANH_NV("Bạn đã hoàn thành nhiệm vụ"
            ,"You have completed the quest"
            ,"你已经完成了任务"
            ,"너는 퀘스트를 완료했다."
            ,"អ្នកបានបញ្ចប់ដំណើរស្វែងរក"
            ,"คุณได้เสร็จสิ้นภารกิจแล้ว"
            ,"ທ່ານໄດ້ສໍາເລັດການຊອກຫາ"
            ,"သင်ကရှာပုံတော်ပြီးစီးခဲ့ပါပြီ"
            ,"Anda telah menyelesaikan misi"),
    NHIEM_VU("Nhiệm vụ"
            ,"Quest"
            ,"任务"
            ,"사명"
            ,"បេសកកម្ម"
            ,"หน้าที่"
            ,"ພາລະກິດ"
            ,"မစ်ရှင်"
            ,"misi"),
    DAP_UNG_NC_LT_QG("Đáp ứng nhu cầu kho lương thực quốc gia"
            ,"Meet the demand of the National Food Storage"
            ,"满足国家食品储存的需求"
            ,"국가 식품 저장 요구 사항 충족"
            ,"បំពេញតម្រូវការនៃចំណីអាហារជាតិ"
            ,"ตอบสนองความต้องการของที่เก็บอาหารแห่งชาติ"
            ,"ຕອບສະຫນອງຄວາມຕ້ອງການຂອງການເກັບຮັກສາອາຫານແຫ່ງຊາດ"
            ,"အမျိုးသားစားနပ်ရိက္ခာသိုလှောင်မှု၏ဝယ်လိုအားနှင့်တွေ့ဆုံရန်"
            ,"Memenuhi permintaan dari Penyimpanan Makanan Nasional"),
    DAT_SOI("Đất sỏi"
            ,"Gravel soil"
            ,"砾石土"
            ,"자갈 토양"
            ,"ដីជីក"
            ,"ดินกรวด"
            ,"ດິນແກນ"
            ,"ကျောက်စရစ်သည်မြေဆီလွှာ"
            ,"Kerikil tanah"),
    BUI_CAY_XANH("Bụi cây xanh"
            ,"Green bush"
            ,"绿色灌木"
            ,"녹색 덤불"
            ,"ព្រៃបៃតង"
            ,"พุ่มไม้สีเขียว"
            ,"ຂຽວຂຽວພຸ່ມ"
            ,"အစိမ်းရောင်ခြုံ"
            ,"semak hijau"),
    BUI_CAY_TRANG("Bụi cây trắng"
            ,"White bush"
            ,"白色的布什"
            ,"흰 덤불"
            ,"ព្រៃពណ៌ស"
            ,"พุ่มไม้สีขาว"
            ,"ພຸ່ມໄມ້ສີຂາວ"
            ,"အဖြူခြုံ"
            ,"semak putih"),
    BUI_CAY_VANG("Bụi cây vàng"
            ,"Yellow bush"
            ,"黄色的布什"
            ,"노란 부시"
            ,"ព្រៃលឿង"
            ,"ព្រៃលឿង"
            ,"ພຸ່ມໄມ້ສີເຫຼືອງ"
            ,"အဝါရောင်ခြုံ"
            ,"semak kuning"),
    BUI_CAY_DO("Bụi cây đỏ"
            ,"Red bush"
            ,"红色的布什"
            ,"빨간 부시"
            ,"ព្រៃក្រហម"
            ,"พุ่มไม้สีแดง"
            ,"ພຸ່ມໄມ້ແດງ"
            ,"အနီရောင်ချုံပုတ်"
            ,"semak merah"),
    BUI_CAY_TIM("Bụi cây tím"
            ,"Purple bush"
            ,"紫色的布什"
            ,"자주색 관목"
            ,"ព្រៃស្វាយ"
            ,"พุ่มสีม่วง"
            ,"ພຸ່ມໄມ້ສີມ່ວງ"
            ,"ခရမ်းရောင်ခြုံ"
            ,"semak ungu"),
    NANG_CAP_TC_LEN_CAP("Nâng cấp thành công lên cấp %d!"
            ,"Upgraded successfully to level %d!"
            ,"成功升级到％d级！"
            ,"레벨 % d (으)로 성공적으로 업그레이드되었습니다!"
            ,"បានដំឡើងកំណែដោយជោគជ័យទៅកម្រិត% d!"
            ,"อัปเกรดเรียบร้อยแล้วถึงระดับ% d!"
            ,"ອັບເກດທີ່ປະສົບຜົນສໍາເລັດໃນລະດັບ% d!"
            ,"အဆင့်% ဃမှအောင်မြင်စွာအဆင့်မြှင့်!"
            ,"Berhasil ditingkatkan ke level% d!"),
    NANG_CAP_THAT_BAI("Nâng cấp thất bại !"
            ,"Upgrade failed!"
            ,"升级失败！"
            ,"업그레이드가 실패했습니다!"
            ,"ការដំឡើងកំណែបរាជ័យ!"
            ,"อัพเกรดล้มเหลว!"
            ,"ອັບເກດລົ້ມເຫລວ!"
            ,"အဆင့်မြှင့်ပျက်ကွက်!"
            ,"Peningkatan gagal!"),
    NANG_CAP_RUONG_D_LEN_CAP("Nâng cấp ruộng %d lên cấp!"
            ,"Upgrade farm %d to level!"
            ,"将农场％d升级到水平！"
            ,"팜 % d을 (를) 수준으로 업그레이드하십시오!"
            ,"ធ្វើបច្ចុប្បន្នភាពកសិកម្ម% d ទៅកម្រិត!"
            ,"อัพเกรดฟาร์ม% d ถึงระดับ!"
            ,"ອັບເກດຟາມ% d ໃນລະດັບ!"
            ,"အဆင့်အဆင့်မြှင့်လယ်ယာ% ဃ!"
            ,"Tingkatkan peternakan% d ke level!"),
    KHO_CHUA_HAT_GIONG("Kho chứa hạt giống"
            ,"Seed Storage"
            ,"种子储存"
            ,"종자 저장"
            ,"ការផ្ទុកគ្រាប់ពូជ"
            ,"การเก็บรักษาเมล็ดพันธุ์"
            ,"ການເກັບຮັກສາເມັດພັນ"
            ,"အမျိုးအနွယ်ကိုသိုလှောင်မှု"
            ,"penyimpanan benih"),
    THUE_1_NHAN_CONG("Thuê 1 nhân công tự động trồng trọt, chăn nuôi\nthu hoạch. Thuê trong 1 mùa"
            ,"Hire 1 labor to plant, to breed and harvest. Hire in 1 farming season."
            ,"雇佣1名农民种植，繁殖和收获。 在农耕季节租用。"
            ,"1 명의 농부를 고용하여 번식시키고 번식시키고 수확하십시오. 1 계절의 농업"
            ,"ជួលកសិករ 1 នាក់ឱ្យដាំដុះដើម្បីចិញ្ចឹមនិងប្រមូលផល។ ជួលនៅរដូវ 1 ។"
            ,"จ้างชาวนา 1 คนปลูกพืชพันธุ์และเก็บเกี่ยว เช่าในฤดูการทำฟาร์ม 1 แห่ง"
            ,"ຈ້າງຊາວນາປູກຕົ້ນໄມ້, ປູກແລະເກັບກ່ຽວ. ຈ້າງໃນ 1 ລະດູການປູກຝັງ."
            ,"သားကိုမွေးခြင်းနှင့်စပါးရိတ်ရာကာလ, စက်ရုံ 1 မှလယ်သမားကိုငှားရမ်း။ 1 လယ်ယာစိုက်ပျိုးရာသီအတွက်ငှားရမ်း။"
            ,"Sewa 1 petani untuk menanam, untuk berkembang biak dan panen. Sewa dalam 1 musim pertanian."),
    THEM_1_CHO_BAN("Thêm 1 chỗ bán nông phẩm trong 1 mùa"
            ,"Add 1 more kiosk in 1 farming season"
            ,"在一个季节添加一个销售农产品的地方"
            ,"계절에 농산물을 판매 할 장소를 추가하십시오."
            ,"បន្ថែមតូប 1 ទៀតក្នុង 1 រដូវដាំដុះ"
            ,"เพิ่มตู้อีก 1 ตู้ในฤดูการทำฟาร์ม 1 แห่ง"
            ,"ເພີ່ມ 1 ໂຕອີກໃນ 1 ລະດູການປູກຝັງ"
            ,"1 လယ်ယာစိုက်ပျိုးရာသီအတွက် 1 ကိုပိုစားပွဲခုံရ"
            ,"Tambahkan 1 meja lagi dalam 1 musim pertanian"),
    NGOC_MM_TANG_TC("Ngọc may mắn tăng thêm 20%\nkhả năng thành công"
            ,"Lucky gem to get 20% of successful"
            ,"幸运宝石获得20％的成功"
            ,"성공의 20 %를 얻는 행운의 보석"
            ,"ត្បូងសំណាងដើម្បីទទួលបានជោគជ័យ 20%"
            ,"อัญมณีโชคดีที่ได้รับ 20% ของความสำเร็จ"
            ,"ແກ້ວປະເສີດທີ່ຈະໄດ້ຮັບ 20% ຂອງປະສົບຜົນສໍາເລັດ"
            ,"အောင်မြင်သော၏ 20% ရဖို့ကံကောင်းကျောက်မျက်"
            ,"Permata beruntung mendapatkan 20% kesuksesan"),
    NC_TB_VUONG_0_GIAM("Nếu nâng cấp vườn thất bại thì\nvườn không bị giảm cấp"
            ,"The farm will not be down level for upgrading failed"
            ,"升级失败后，服务器场不会降级"
            ,"실패한 업그레이드를 위해 팜이 수준을 낮추지 않습니다."
            ,"កសិដ្ឋាននឹងមិនត្រូវបានធ្លាក់ចុះកម្រិតសម្រាប់ការធ្វើឱ្យប្រសើរបានបរាជ័យ"
            ,"ฟาร์มจะไม่ลดระดับสำหรับการอัพเกรดล้มเหลว"
            ,"ກະສິກໍາຈະບໍ່ຫຼຸດລົງໃນລະດັບການຍົກລະດັບບໍ່ໄດ້"
            ,"အဆိုပါလယ်ယာမှုမအောင်မြင်ပါအဆင့်မြှင့်ဘို့အဆင့်ကိုနှိမ့်ချလိမ့်မည်မဟုတ်ပေ"
            ,"Peternakan tidak akan turun tingkat karena peningkatan gagal"),
    KHO_CHUA_NONG_PHAM("Kho chứa nông phẩm"
            ,"Farm Product Storage"
            ,"农产品存储"
            ,"농산물 저장"
            ,"ការផ្ទុកផលិតផលកសិដ្ឋាន"
            ,"ที่จัดเก็บผลิตภัณฑ์ฟาร์ม"
            ,"ນາເກັບສິນຄ້າ"
            ,"လယ်ယာကုန်ပစ္စည်းသိုလှောင်ခြင်း"
            ,"Penyimpanan Hasil Pertanian"),
    CHON_NP_DE_BAN("Chọn nông phẩm để bán"
            ,"Select products to sell"
            ,"选择要销售的产品"
            ,"판매 할 제품 선택"
            ,"ជ្រើសរើសផលិតផលដើម្បីលក់"
            ,"เลือกผลิตภัณฑ์ที่จะขาย"
            ,"ເລືອກຜະລິດຕະພັນທີ່ຈະຂາຍ"
            ,"ရောင်းဖို့ထုတ်ကုန်ကိုရှေးခယျြ"
            ,"pilih produk untuk dijual"),
    MUA_GAME_TC("Chúc mừng bạn đã mua game thành công !"
            ,"Congratulation on purchasing game successfully!"
            ,"祝贺您成功购买游戏！"
            ,"게임을 성공적으로 구매하신 것을 축하합니다!"
            ,"សូមអបអរសាទរក្នុងការទិញល្បែងដោយជោគជ័យ!"
            ,"ขอแสดงความยินดีกับการซื้อเกมเรียบร้อยแล้ว!"
            ,"ຊົມເຊີຍໃນການຊື້ເກມໄດ້ປະສົບຜົນສໍາເລັດ!"
            ,"အောင်မြင်စွာဂိမ်းဝယ်ယူအပေါ်!"
            ,"Selamat telah membeli game dengan sukses!"),
    KHONG_DU_XU_MUA_("Bạn không đủ xu để mua game !"
            ,"You do not have enough cash to purchase this game!"
            ,"你没有足够的现金购买这个游戏！"
            ,"이 게임을 구입하기에 충분한 현금이 없습니다!"
            ,"អ្នកមិនមានប្រាក់គ្រប់គ្រាន់ដើម្បីទិញហ្គេមនេះទេ!"
            ,"คุณไม่มีเงินสดเพียงพอที่จะซื้อเกมนี้!"
            ,"ທ່ານບໍ່ມີເງິນສົດພຽງພໍທີ່ຈະຊື້ເກມນີ້!"
            ,"သင်ဤဂိမ်းဝယ်ယူရန်လုံလောက်သောငွေရှိသည်မဟုတ်ကြဘူး!"
            ,"Anda tidak memiliki cukup uang untuk membeli game ini!"),
    YEAR("Năm"
            ,"Year"
            ,"年"
            ,"년"
            ,"ឆ្នាំ"
            ,"ปี"
            ,"ປີ"
            ,"ခုနှစ်"
            ,"tahun"),
    CHUNG_CU("Chung cư"
            ,"Condominium"
            ,"共管"
            ,"분양 아파트"
            ,"ខុនដូ"
            ,"คอนโดมิเนียม"
            ,"ຄອນໂດມິນຽມ"
            ,"ကွန်ဒိုမီနီယံ"
            ,"kondominium"),
    CONG_VIEN("Công viên"
            ,"Park"
            ,"公园"
            ,"공원"
            ,"ឧទ្យាន"
            ,"จอด"
            ,"ສວນສະຫນຸກ"
            ,"ပန်းခြံ"
            ,"taman"),
    CUA_HANG_CAFE("Cửa hàng\nCafe"
            ,"Coffee shop"
            ,"咖啡店"
            ,"커피 샵"
            ,"ហាង​កាហ្វេ"
            ,"ร้านกาแฟ"
            ,"ຮ້ານ​ກາ​ເຟ"
            ,"ကော်ဖီဆိုင်"
            ,"kedai kopi"),
    CUA_HANG_FASTFOOD("Cửa hàng\nFastfood"
            ,"Fastfood Restaurant"
            ,"快餐店"
            ,"패스트 푸드 레스토랑"
            ,"ភោជនីយដ្ឋានអាហារលឿន"
            ,"ร้านอาหารฟาสฟู้ด"
            ,"ຮ້ານອາຫານຈານດ່ວນທັງຫມົດ"
            ,"အမြန်ပြင်အစားအစာစားသောက်ဆိုင်"
            ,"Restoran cepat saji"),
    KHACH_SAN("Khách sạn"
            ,"Hotel"
            ,"旅馆"
            ,"호텔"
            ,"សណ្ឋាគារ"
            ,"โรงแรม"
            ,"ໂຮງແຮມ"
            ,"ဟော်တယ်"
            ,"hotel"),
    KHO_LUONG_THUC("Kho lương thực"
            ,"National Food Storage"
            ,"国家食品储存"
            ,"국가 식품 저장"
            ,"ការផ្ទុកអាហារជាតិ"
            ,"การจัดเก็บอาหารแห่งชาติ"
            ,"ການເກັບຮັກສາອາຫານແຫ່ງຊາດ"
            ,"အမျိုးသားရေးအစားအစာသိုလှောင်မှု"
            ,"penyimpanan makanan nasional"),
    NHA_GA("Nhà ga"
            ,"Station"
            ,"站"
            ,"역"
            ,"ស្ថានីយ៍"
            ,"สถานี"
            ,"ສະຖານີ"
            ,"ဘူတာရုံ"
            ,"stasiun"),
    NHA_HANG_NHAT("Nhà hàng\nNhật"
            ,"Japanese Restaurant"
            ,"日本餐厅"
            ,"일본 레스토랑"
            ,"ភោជនីយដ្ឋានជប៉ុន"
            ,"ร้านอาหารญี่ปุ่น"
            ,"ຮ້ານອາຫານຍີ່ປຸ່ນ"
            ,"ဂျပန်စားသောက်ဆိုင်"
            ,"restoran Jepang"),
    TRUONG_HOC("Trường học"
            ,"School"
            ,"学校"
            ,"학교"
            ,"សាលារៀន"
            ,"โรงเรียน"
            ,"ໂຮງຮຽນ"
            ,"ကြောငျး"
            ,"sekolah"),
    VAN_PHONG("Văn phòng"
            ,"Office"
            ,"办公室"
            ,"사무실"
            ,"ការិយាល័យ"
            ,"สำนักงาน"
            ,"ຫ້ອງການ"
            ,"ရုံး"
            ,"kantor"),
    VUON_HOA("Vườn hoa"
            ,"Garden"
            ,"花园"
            ,"정원"
            ,"សួន"
            ,"สวน"
            ,"ສວນ"
            ,"ဥယျာဉ်တော်"
            ,"taman"),
    VUON_THU("Vườn thú"
            ,"Zoo"
            ,"动物园"
            ,"동물원"
            ,"សួនសត្វ"
            ,"สวนสัตว์"
            ,"ສວນສັດ"
            ,"တရိစ်ာဆနျရုံ"
            ,"kebun binatang"),
    CAP_DO("Cấp độ:"
            ,"Level:"
            ,"水平："
            ,"수평:"
            ,"កម្រិត:"
            ,"ระดับ:"
            ,"ລະດັບ:"
            ,"အဆငျ့:"
            ,"tingkat:"),
    HUONG_DAN("Hướng dẫn"
            ,"Guide"
            ,"指南"
            ,"안내서"
            ,"ណែនាំ"
            ,"แนะนำ"
            ,"ແນະນໍາ"
            ,"လမ်းညွှန်"
            ,"panduan"),
    HUONG_DAN_1("Cửa hàng: nơi bán hạt giống và vật phẩm"
            ,"Shop: sell seeds and products"
            ,"商店：出售种子和产品"
            ,"상점 : 종자 및 제품 판매"
            ,"ហាង: លក់គ្រាប់ពូជនិងផលិតផល"
            ,"ร้านค้า: ขายเมล็ดพันธุ์และผลิตภัณฑ์"
            ,"ຮ້ານ: ຂາຍແກ່ນແລະຜະລິດຕະພັນ"
            ,"ဆိုင်: ရောင်းမျိုးစပါးနှင့်ထုတ်ကုန်"
            ,"toko: jual benih dan produk"),
    HUONG_DAN_2("Kho chứa: giúp kiểm tra số cây trồng còn lại"
            ,"Storage: keeps the plants you have"
            ,"储存：保存您拥有的植物"
            ,"저장 : 가지고있는 식물 유지"
            ,"ឧបករណ៍ផ្ទុក: រក្សារុក្ខជាតិដែលអ្នកមាន"
            ,"พื้นที่เก็บข้อมูล: ช่วยเก็บรักษาพืชที่คุณมีอยู่"
            ,"ການເກັບຮັກສາ: ເຮັດໃຫ້ພືດທີ່ທ່ານມີ"
            ,"သိုလှောင်မှု: သင်ရှိသည်ပင်စောင့်ရှောက်"
            ,"Penyimpanan: simpan tanaman yang Anda miliki"),
    HUONG_DAN_3("Hạt giống: lấy hạt giống để trồng cây"
            ,"Seed: seeds to plant the tree"
            ,"种子：种子种植树"
            ,"종자 : 나무 심는 씨앗"
            ,"ពូជ: គ្រាប់ពូជដើម្បីដាំដើមឈើ"
            ,"เมล็ด: เมล็ดปลูกต้นไม้"
            ,"ແກ່ນ: ແກ່ນເພື່ອປູກຕົ້ນໄມ້"
            ,"အမြိုးအနှယျ: မျိုးစပါးသစ်ပင်စိုက်ရန်"
            ,"Biji: biji untuk menanam pohon"),
    HUONG_DAN_4("Cái xẻng: giúp nhổ bỏ cây trồng"
            ,"Shovel: helps you to root up the trees"
            ,"铲：帮助你扎根树木"
            ,"삽 : 나무를 뿌리 내리는 데 도움이됩니다."
            ,"ប៉េល: ជួយអ្នកក្នុងការរុះរើដើមឈើ"
            ,"พลั่ว: ช่วยให้คุณปลูกราก"
            ,"ຊ້ວນ: ຊ່ວຍໃຫ້ທ່ານສາມາດຮາກຕົ້ນໄມ້ໄດ້"
            ,"ဂေါ်ပြား: သင်သစ်ပင်များကိုတက် root စေရန်ကူညီပေးသည်"
            ,"Sekop: membantu Anda membasmi pepohonan"),
    HUONG_DAN_5("Người giúp việc: điều chỉnh thứ tự\nưu tiên trồng các loại cây"
            ,"Housekeeper: Helps you to arrange the priority position of trees"
            ,"管家：帮助您安排树木的优先位置"
            ,"가정부 : 나무의 우선 순위를 정하는 데 도움을줍니다."
            ,"អ្នកចាត់ចែង: ជួយអ្នករៀបចំទីតាំងអាទិភាពនៃដើមឈើ"
            ,"แม่บ้าน: ช่วยให้คุณจัดลำดับความสำคัญของต้นไม้"
            ,"ໄມ: ຊ່ວຍໃຫ້ທ່ານສາມາດຈັດຕໍາແຫນ່ງບູລິມະສິດຂອງຕົ້ນໄມ້"
            ,"နေရာထိုင်ခင်းထိန်းသိမ်းရေး: သင်သစ်ပင်များ၏ဦးစားပေးအနေအထားကိုစီစဉ်ဖို့ကူညီပေး"
            ,"Pengurus rumah tangga: Membantu Anda mengatur posisi prioritas pohon"),
    HUONG_DAN_6("Cuộn giấy: Xem thông tin nhiệm vụ\nhiện tại"
            ,"Roll paper: to read the information of quests"
            ,"卷纸：阅读使命信息"
            ,"롤 용지 : 임무의 정보를 읽는"
            ,"រមៀលក្រដាស: ដើម្បីអានពត៌មាននៃបេសកកម្ម"
            ,"ม้วนกระดาษ: เพื่ออ่านข้อมูลของภารกิจ"
            ,"ເຈ້ຍ: ເພື່ອອ່ານຂໍ້ມູນຂອງພາລະກິດ"
            ,"လိပ်စက္ကူ: ရှာဖေွခြင်း၏သတင်းအချက်အလက်များကိုဖတ်ရှုဖို့"
            ,"Gulung kertas: untuk membaca informasi dari pencarian"),
    HUONG_DAN_7("Thị trường sáng màu:\n    có thể giao dịch được"
            ,"The bright market: can trade"
            ,"光明的市场：可以交易"
            ,"밝은 시장 : 교역 할 수있다."
            ,"ទីផ្សារភ្លឺ: អាចធ្វើពាណិជ្ជកម្ម"
            ,"ตลาดที่สดใส: สามารถซื้อขายได้"
            ,"ຕະຫຼາດສົດໃສ: ສາມາດຄ້າຂາຍ"
            ,"ထွန်းတောက်စျေးကွက်: ရောင်းဝယ်ဖောက်နိုင်"
            ,"Pasar yang cerah: dapat berdagang"),
    HUONG_DAN_8("Thị trường tối màu:\n     chưa thể giao dich được"
            ,"The dark market: cannot trade"
            ,"黑市：无法交易"
            ,"어두운 시장 : 교역 할 수 없다."
            ,"ទីផ្សារងងឹត: មិនអាចធ្វើពាណិជ្ជកម្ម"
            ,"ตลาดที่มืด: ไม่สามารถซื้อขายได้"
            ,"ຕະຫຼາດຊ້ໍາ: ບໍ່ສາມາດຄ້າ"
            ,"မှောင်မိုက်စျေးကွက်: ကုန်သွယ်မှုနိုင်ဘူး"
            ,"Pasar gelap: tidak bisa berdagang"),
    HUONG_DAN_9("Kho lương thực quốc gia:\n  nhiệm vụ cần làm trước khi\n     hết thời gian quy định"
            ,"The National Food Storage:  Quest need to be done  before running out of time"
            ,"国家食品储存：任务需要在用完之前完成"
            ,"국가 식품 저장 : 시간이 부족하기 전에 퀘스트를 수행해야합니다."
            ,"ការស្តុកស្បៀងអាហារជាតិ: ដំណើរស្វែងរកត្រូវបានគេធ្វើមុនពេលរត់ចេញពីពេលវេលា"
            ,"ที่เก็บอาหารแห่งชาติ: เควสต้องทำก่อนหมดเวลา"
            ,"ການເກັບຮັກສາອາຫານແຫ່ງຊາດ: ພາລະກິດຕ້ອງເຮັດກ່ອນທີ່ຈະຫມົດເວລາ"
            ,"အမျိုးသားစားနပ်ရိက္ခာသိုလှောင်မှု: မစ်ရှင်အချိန်ထဲကမတိုင်မီအမှုကိုပြုခံရဖို့လိုအပ်"
            ,"Penyimpanan Makanan Nasional: Misi harus dilakukan sebelum kehabisan waktu"),
    HUONG_DAN_10("Sau khi mở giao dịch\nbạn có thể tạm ngừng giao dịch nếu cần thiết"
            ,"After opening a trade you can temporarily close it (if it is necessary)"
            ,"开盘后你可以暂时关闭它（如果有必要的话）"
            ,"거래를 한 후에는 일시적으로 거래를 마감 할 수 있습니다 (필요한 경우)."
            ,"បន្ទាប់ពីបើកការជួញដូរមួយអ្នកអាចបិទវាជាបណ្តោះអាសន្ន (ប្រសិនបើវាចាំបាច់)"
            ,"หลังจากเปิดทำการค้าคุณสามารถปิดชั่วคราวได้ (ถ้าจำเป็น)"
            ,"ຫຼັງຈາກເປີດການຄ້າທ່ານສາມາດປິດມັນໄດ້ຊົ່ວຄາວ (ຖ້າມັນມີຄວາມຈໍາເປັນ)"
            ,"ဖွင့်လှစ်ပြီးနောက်သင်ယာယီပိတ်လို့ရပါတယ်"
            ,"Setelah membuka perdagangan, Anda dapat menutupnya untuk sementara waktu (jika perlu)"),
    TAM_DUNG_MUA_BAN("Tạm dừng\nmua bán"
            ,"Pause\nSale"
            ,"暂停\n拍卖"
            ,"중지\n판매"
            ,"ផ្អាក\nលក់"
            ,"หยุด\nการขาย"
            ,"ຢຸດ​ຊົ່ວ​ຄາວ\nຂາຍ"
            ,"ခေတ္တရပ်ဆိုင်း\nရောင်းချခြင်း"
            ,"Berhenti sebentar\nPenjualan"),
    TIEP_TUC_MUA_BAN("Tiếp tục\nmua bán"
            ,"Continue\nSale"
            ,"继续\n拍卖"
            ,"잇다\n판매"
            ,"បន្ត\nលក់"
            ,"ต่อ\nการขาย"
            ,"ສືບຕໍ່\nຂາຍ"
            ,"ဆက်လက်ရော\nင်းချခြင်း"
            ,"Terus\nPenjualan"),
    NONG_TRAI("Nông trại"
            ,"Farm"
            ,"农场"
            ,"농장"
            ,"កសិដ្ឋាន"
            ,"ฟาร์ม"
            ,"ກະສິກໍາ"
            ,"လယ်ယာ"
            ,"tanah pertanian"),
    NONG_TRAI_DA_QUA("Nông trại đã qua %d mùa hạnh phục"
            ,"The farm has passed the happy season"
            ,"农场度过了快乐的季节"
            ,"농장은 행복한 계절을 보냈습니다."
            ,"កសិដ្ឋាននេះបានកន្លងផុតទៅរដូវកាលរីករាយ"
            ,"ฟาร์มผ่านฤดูกาลแห่งความสุขแล้ว"
            ,"ກະສິກໍາໄດ້ຜ່ານລະດູການທີ່ມີຄວາມສຸກ"
            ,"အဆိုပါလယ်ယာပျြောရှငျသောရာသီလွန်ပြီ"
            ,"Peternakan telah melewati musim bahagia"),
    XD_NT_TO_DEP("Tiếp tục xây dựng nông trại to đẹp hơn nữa!"
            ,"Let's keep building a bigger and prettier farm!"
            ,"让我们继续建设一个更大，更漂亮的农场！"
            ,"더 크고 더 예쁜 농장을 짓 읍시다!"
            ,"ចូរបន្តបង្កើតកសិដ្ឋានធំជាងមុននិងស្រស់ស្អាតជាងមុន!"
            ,"ลองสร้างฟาร์มที่ใหญ่กว่าและน่ารักมากขึ้น!"
            ,"ໃຫ້ສືບຕໍ່ກໍ່ສ້າງຟາມຂະຫນາດໃຫຍ່ແລະສວຍງາມ!"
            ,"ပိုကြီးနှင့်တော်တော်လေးလယ်ယာတည်ဆောက်ခြင်းစောင့်ရှောက်ကြပါစို့!"
            ,"Mari terus membangun pertanian yang lebih besar dan lebih cantik!"),
    LEN_CAP("Lên cấp"
            ,"Level up"
            ,"升级"
            ,"레벨 업"
            ,"ឡើង​កម្រិត"
            ,"ยกระดับ"
            ,"ການຍົກລະດັບ"
            ,"တက်ညီ"
            ,"naik tingkat"),
    HT_NHIEM_VU("Hoàn thành nhiệm vụ"
            ,"Completed Quest"
            ,"完成任务"
            ,"임무 완수"
            ,"បំពេញបេសកកម្ម"
            ,"ภารกิจที่เสร็จสมบูรณ์"
            ,"ພາລະກິດທີ່ສົມບູນ"
            ,"ပြီးစီးခဲ့မစ်ရှင်"
            ,"misi selesai"),
    DANG_YEU("Đáng yêu"
            ,"Cute"
            ,"可爱"
            ,"귀엽다"
            ,"គួរឱ្យស្រលាញ់"
            ,"น่ารัก"
            ,"ງາມ"
            ,"ချစ်စရာ"
            ,"imut"),
    GIAU_CO("Giàu có"
            ,"Wealth"
            ,"财富"
            ,"풍부한"
            ,"ទ្រព្យសម្បត្តិ"
            ,"ความมั่งคั่ง"
            ,"ຄວາມຮັ່ງມີ"
            ,"ဥစ္စာဓန"
            ,"kekayaan"),
    HIEU_KHACH("Hiếu khách"
            ,"Hospitality"
            ,"待客"
            ,"환대"
            ,"បដិសណ្ឋារកិច្ច"
            ,"การต้อนรับขับสู้"
            ,"ການຕ້ອນຮັບ"
            ,"ဧညျ့ဝတျကပြွှေနျခွငျး"
            ,"keramahan"),
    VUI_VE("Vui vẻ"
            ,"Cheerful"
            ,"高兴"
            ,"쾌활한"
            ,"ដោយ​ចិត្ដ​រីករាយ"
            ,"ร่าเริง"
            ,"ມີຄວາມສຸກ"
            ,"ရွှင်လန်းသော"
            ,"riang"),
    HANH_PHUC("Hạnh phúc"
            ,"Happy"
            ,"快乐"
            ,"행복"
            ,"រីករាយ"
            ,"มีความสุข"
            ,"ຍິນດີ"
            ,"ပျြောရှငျသော"
            ,"senang"),
    THAN_THIEN("Thân thiện"
            ,"Nice"
            ,"可亲"
            ,"좋은"
            ,"ល្អ"
            ,"ดี"
            ,"ດີ"
            ,"ကောင်းတဲ့"
            ,"bagus"),
    TANG_1_NC_THAN("Tặng 1 nước thần"
            ,"Give a god water"
            ,"给神水"
            ,"신의 물을주십시오."
            ,"ផ្តល់ទឹកឱ្យព្រះ"
            ,"ให้น้ำพระเจ้า"
            ,"ໃຫ້ນ້ໍາພຣະເຈົ້າ"
            ,"ဘုရားရေ Give"
            ,"Berikan air dewa"),
    QUA_TANG_TAN_GIA("QÙA TẶNG TÂN GIA"
            ,"GIFT"
            ,"礼品"
            ,"선물"
            ,"អំណោយ"
            ,"ของขวัญ"
            ,"GIFT"
            ,"လကျဆောငျ"
            ,"HADIAH"),
    PHUT_GIAY_VUI_VE("Hi vọng bạn sẽ có\nnhững phút giây\nthật sự vui vẻ !"
            ,"Hope that you will have happy moments!"
            ,"希望你有幸福的时刻！"
            ,"행복한 순간을 가지기를 바랍니다!"
            ,"សង្ឃឹមថាអ្នកនឹងមានឱកាសសប្បាយរីករាយ!"
            ,"หวังว่าคุณจะมีช่วงเวลาแห่งความสุข!"
            ,"ຫວັງວ່າທ່ານຈະມີຄວາມສຸກໃນປັດຈຸບັນ!"
            ,"သငျသညျမင်ျဂလာအချိန်လေးရှိလိမ့်မည်ဟုမျှော်လင့်ပါတယ်!"
            ,"Semoga Anda akan memiliki saat-saat bahagia!"),
    HET_GIO_SD_NHAN_CONG("Hết thời gian sử dụng\nnhân công tự động.\n\n Để sử dụng \t\t\t\t\t\nhân công tự \nđộng bạn hãy vào cửa hàng \nđể mua nhé !"
            ,"You cannot use automatic farmer now. Go to shop now!"
            ,"你现在不能使用自动农民。 现在去购物！"
            ,"지금 자동 농부는 사용할 수 없습니다. 지금 가게에 가세요!"
            ,"ឥឡូវនេះអ្នកមិនអាចប្រើប្រាស់កសិករដោយស្វ័យប្រវត្តិបានទេ។ សូមទៅទិញឥវ៉ាន់ឥឡូវនេះ!"
            ,"คุณไม่สามารถใช้เกษตรกรโดยอัตโนมัติได้เลย ไปที่ร้านตอนนี้!"
            ,"ທ່ານບໍ່ສາມາດນໍາໃຊ້ຊາວກະສິກອນແບບອັດຕະໂນມັດໄດ້ທັນທີ. ໄປຊື້ເຄື່ອງໃນຕອນນີ້!"
            ,"သငျသညျယခုအော်တိုလယ်သမားကိုမသုံးနိုငျသညျ။ ယခုစျေးဝယ်သွားပါ"
            ,"Anda tidak dapat menggunakan petani otomatis sekarang. Pergi berbelanja sekarang!"),
    NUOC_THAN("Nước thần"
            ,"God water"
            ,"神水"
            ,"하느님의 물"
            ,"ព្រះទឹក"
            ,"พระเจ้าน้ำ"
            ,"ພຣະເຈົ້ານ້ໍາ"
            ,"ဘုရားသခငျသညျရေ"
            ,"Air Tuhan"),
    MUA_XUAN("Mùa xuân"
            ,"Spring"
            ,"春天"
            ,"봄"
            ,"និទាឃរដូវ"
            ,"ฤดูใบไม้ผลิ"
            ,"ຜາດໂຜນ"
            ,"နွေဦး"
            ,"musim semi"),
    MUA_HA("Mùa hạ"
            ,"Summer"
            ,"夏天"
            ,"여름"
            ,"រដូវក្តៅ"
            ,"ฤดูร้อน"
            ,"ຮ້ອນ"
            ,"နွေရာသီ"
            ,"musim panas"),
    MUA_THU("Mùa thu"
            ,"Autumn"
            ,"秋天"
            ,"가을"
            ,"រដូវស្លឹកឈើជ្រុះ"
            ,"ฤดูใบไม้ร่วง"
            ,"ດູໃບໄມ້ລົ່ນ"
            ,"ဆောင်းဉီးရာသီ"
            ,"musim gugur"),
    MUA_DONG("Mùa đông"
            ,"Winter"
            ,"冬季"
            ,"겨울"
            ,"រដូវរងា"
            ,"ฤดูหนาว"
            ,"ລະ​ດູ​ຫນາວ"
            ,"ဆောငျးရာသီ"
            ,"musim dingin"),
    TAM_DUNG("Tạm dừng"
            ,"Pause"
            ,"暂停"
            ,"중지"
            ,"ផ្អាក"
            ,"หยุด"
            ,"ຢຸດ​ຊົ່ວ​ຄາວ"
            ,"ခေတ္တရပ်ဆိုင်း"
            ,"berhenti sebentar"),
    NANG_CAP("Nâng cấp"
            ,"Upgrade"
            ,"升级"
            ,"업그레이드"
            ,"ធ្វើឱ្យប្រសើរ"
            ,"อัพเกรด"
            ,"ຍົກລະດັບ"
            ,"အဆင့်မြှင့်"
            ,"meningkatkan"),
    CHI_PHI("Chi phí"
            ,"Cost"
            ,"成本"
            ,"비용"
            ,"តម្លៃ"
            ,"ราคา"
            ,"ຄ່າໃຊ້ຈ່າຍ"
            ,"ပေးရ"
            ,"biaya"),
    SU_DUNG_THEM("Sử dụng thêm"
            ,"Use more"
            ,"使用更多"
            ,"더 많이 사용하다"
            ,"ប្រើច្រើនទៀត"
            ,"ใช้มากขึ้น"
            ,"ໃຊ້ຫຼາຍ"
            ,"ပိုပြီးအသုံးပြုနိုင်သည်"
            ,"gunakan lebih banyak"),
    TANG("Tăng"
            ,"Up"
            ,"向上"
            ,"쪽으로"
            ,"ឡើង"
            ,"ขึ้น"
            ,"ຂຶ້ນ"
            ,"အထက်"
            ,"naik"),
    GIAM("Giảm"
            ,"Down"
            ,"向下"
            ,"하위"
            ,"ចុះក្រោម"
            ,"ลง"
            ,"ລົງ"
            ,"နှိမ့်ချ"
            ,"turun"),
    KINH_NGHIEM_KHI_THU("Kinh nghiệm khi thu hoạch"
            ,"Experience in harvest"
            ,"丰收经验"
            ,"수확 체험"
            ,"បទពិសោធន៍ក្នុងការប្រមូលផល"
            ,"ประสบการณ์ในการเก็บเกี่ยว"
            ,"ປະສົບການໃນການຂຸດຄົ້ນ"
            ,"စပါးရိတ်ရာကာလအတွေ့အကြုံ"
            ,"Pengalaman dalam panen"),
    THOI_GIAN_KHI_THU("Thời gian khi thu hoạch"
            ,"Time to harvest"
            ,"是时候收获了"
            ,"수확 할 시간"
            ,"ពេលវេលាដើម្បីប្រមូលផល"
            ,"เวลาในการเก็บเกี่ยว"
            ,"ເວລາທີ່ຈະເກັບກ່ຽວ"
            ,"ရိတ်ဖို့အချိန်"
            ,"Saatnya panen"),
    MO_RONG_DAT("Mở rộng đất"
            ,"Expand the land"
            ,"扩大土地"
            ,"땅을 넓히다"
            ,"ពង្រីកដី"
            ,"ขยายที่ดิน"
            ,"ຂະຫຍາຍດິນ"
            ,"ထိုပြည်ကိုတိုးချဲ့"
            ,"memperluas lahan"),
    MO_RONG("Mở rộng"
            ,"Expand"
            ,"扩大"
            ,"넓히다"
            ,"ពង្រីកដី"
            ,"ขยายตัว"
            ,"ຂະຫຢາຢອອກ"
            ,"တိုးချဲ့"
            ,"memperluas "),
    BN_MUON_NHO_CAY("Bạn muốn nhổ cây đi hay không?"
            ,"Do you want to root out the tree?"
            ,"你想要树根吗？"
            ,"나무를 뿌리 치고 싶니?"
            ,"តើអ្នកចង់ដកដើមឈើចេញទេ?"
            ,"คุณต้องการที่จะรากออกต้นไม้หรือไม่?"
            ,"ທ່ານຕ້ອງການ root ອອກຕົ້ນໄມ້ບໍ?"
            ,"သင်သစ်ပင်ထွက်ချင်ပါသလား?"
            ,"Apakah Anda ingin keluar dari pohon?"),
    GIA_BAN_NHANH("Giá bán nhanh"
            ,"Quick price"
            ,"价格快"
            ,"빠른 가격"
            ,"តម្លៃរហ័ស"
            ,"ราคาด่วน"
            ,"ລາຄາໄວ"
            ,"quick စျေးနှုန်း"
            ,"Harga cepat"),
    NHAP_SO_LUONG("Nhập số lượng"
            ,"Enter the quantity"
            ,"输入数量"
            ,"수량 입력"
            ,"បញ្ចូលបរិមាណ"
            ,"ป้อนปริมาณ"
            ,"ໃສ່ຈໍານວນ"
            ,"အရေအတွက်ရိုက်ထည့်ပါ"
            ,"masukkan kuantitas"),
    TONG_SO_TIEN("Tổng số tiền"
            ,"Total Price"
            ,"总价"
            ,"총 가격"
            ,"តម្លៃ​សរុប"
            ,"ราคารวม"
            ,"ລາ​ຄາ​ລວມ"
            ,"စုစုပေါင်းစျေးနှုန်း"
            ,"total harga"),
    NAP_XU("Nạp xu"
            ,"Deposit cash"
            ,"存款现金"
            ,"예금 현금"
            ,"ដាក់ប្រាក់"
            ,"ฝากเงินสด"
            ,"ຝາກເງິນສົດ"
            ,"သိုက်ငွေသား"
            ,"setor tunai"),
    TXT_NHAN("Nhận"
            ,"Receive"
            ,"接收"
            ,"받다"
            ,"ទទួលបាន"
            ,"รับ"
            ,"ໄດ້ຮັບ"
            ,"ခံယူ"
            ,"menerima"),
    Confirm("Xác nhận"
            ,"Confirm"
            ,"确认"
            ,"확인하다"
            ,"បញ្ជាក់"
            ,"ยืนยัน"
            ,"ຢືນຢັນ"
            ,"အတည်ပြု"
            ,"memastikan"),
    Accept("Đồng ý"
            ,"Accept"
            ,"接受"
            ,"받아 들인다"
            ,"ទទួលយក"
            ,"ยอมรับ"
            ,"ຍອມ​ຮັບ"
            ,"သဘောတူလက်ခံ"
            ,"menerima"),
    ADD_MONEY_VIEW_AD("Bạn nhận được %d xu!"
            , "You recive %d money!"
            ,"你收到%d块钱"
            ,"당신은 %d 돈을받습니다!"
            ,"អ្នកទទួលបានប្រាក់ %d!"
            ,"คุณได้รับเงิน %d!"
            ,"ທ່ານໄດ້ຮັບ %d ເງິນ!"
            ,"သငျသညျ %d ပိုက်ဆံလက်ခံရရှိ!"
            ,"Anda menerima %d uang!"),;

        String languageVN, languageEn, languageCN, languageKR, languageCam, languageThai, languageLaos, languageMyanmar, languageIndo;

        General(String strVn
                , String strEn
                , String strCN
                , String strKR
                , String strCam
                , String strThai
                , String strLaos
                , String strMy
                , String strIndo) {
            this.languageVN = strVn;
            this.languageEn = strEn;
            this.languageCN = strCN;
            this.languageKR = strKR;
            this.languageCam = strCam;
            this.languageThai = strThai;
            this.languageLaos = strLaos;
            this.languageMyanmar = strMy;
            this.languageIndo = strIndo;
        }

        public String getStr() {
            switch (F.language) {
//                case VN:
//                    break;
                case EN:
                    return languageEn;
                case CHINA:
                    return languageCN;
                case KOREAN:
                    return languageKR;
                case CAMBODIA:
                    return languageCam;
                case THAI:
                    return languageThai;
                case LAOS:
                    return languageLaos;
                case MYANMAR:
                    return languageMyanmar;
                case INDO:
                    return languageIndo;
                default:
                    return languageVN;
            }
        }

    }


}
